(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const clone=x=>JSON.parse(JSON.stringify(x));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const round3=n=>Math.round(n*1000)/1000;
const fmt=s=>{s=Math.max(0,+s||0);const m=Math.floor(s/60),sec=s-m*60;return `${String(m).padStart(2,'0')}:${sec.toFixed(3).padStart(6,'0')}`};
const VIDEO=new Set(['intro','vertical','horizontal','video','clip','vertical_clip','horizontal_video']);
const WORKFLOW=['PENDIENTE','REVISADO','HACIENDO','LISTO','PROGRAMADO','PUBLICADO'];
const TRACKS=['captions','music','sfx','vo','broll','motion','images','xr','aroll'];
const TRACK_LABELS={captions:'T9 CAPTIONS',music:'T8 MUSIC',sfx:'T7 SFX',vo:'T6 VO',broll:'T5 B-ROLL',motion:'T4 MOTION',images:'T3 IMAGES',xr:'T2 XR',aroll:'T1 A-ROLL'};
const embedded=JSON.parse($('#app-data').textContent||'{}');
const base=clone(embedded);
const state={project:clone(embedded),mergeBase:clone(base),selectedPieceId:null,selectedEventId:null,selectedStaticId:null,view:'editor',scale:18,history:{undo:[],redo:[]},gesture:null,suppressClickUntil:0,calendar:new Date(),renderer:embedded.renderer?.id||'joc-classic',mergeSession:null,routeByPiece:{}};
document.documentElement.dataset.theme=embedded.renderer?.theme||embedded.canvas?.theme||'dark';
function pid(p){return clean(p?.canonicalId||p?.contentId||p?.content_id||p?.uid||p?.id)}
function ptype(p){return clean(p?.type||p?.kind||'note').toLowerCase()}
function pieces(){return (state.project.pieces||[]).filter(x=>x&&typeof x==='object')}
function getPiece(id){return pieces().find(p=>pid(p)===id)||null}
function currentPiece(){let p=getPiece(state.selectedPieceId);if(!p&&pieces()[0]){p=pieces()[0];state.selectedPieceId=pid(p)}return p}
function getEvent(id){for(const p of pieces())for(const e of p.timeline||[])if(e?.id===id)return e;return null}
function currentEvent(){return getEvent(state.selectedEventId)}
function assetKey(a){return clean(a?.assetId||a?.id||a?.localId)}
function assetRefs(assetId){const refs=[];if(!assetId)return refs;for(const p of pieces())for(const e of p.timeline||[]){if(e?.asset&&assetKey(e.asset)===assetId)refs.push(e.asset);for(const a of e?.assets||[])if(assetKey(a)===assetId)refs.push(a)}return refs}
function syncAssetField(assetId,key,value){for(const ref of assetRefs(assetId))ref[key]=value}
function availableRoutes(p){const routes=new Set();if(p?.storyScripts&&typeof p.storyScripts==='object')for(const key of Object.keys(p.storyScripts))routes.add(String(key));for(const e of p?.timeline||[])for(const r of e?.routes||[])routes.add(String(r));return routes.size?[...routes]:['source']}
function currentRoute(p){const id=pid(p),routes=availableRoutes(p),saved=state.routeByPiece[id];if(saved&&routes.includes(saved))return saved;const preferred=routes.includes('voA')?'voA':routes.includes('source')?'source':routes[0];state.routeByPiece[id]=preferred;return preferred}
function routeEvents(p){const route=currentRoute(p);return (p?.timeline||[]).filter(e=>{const routes=Array.isArray(e?.routes)?e.routes:[];return !routes.length||routes.includes(route)})}
function duration(p){return Math.max(1,...routeEvents(p).map(e=>+e.end||0))}
function routeLabel(route){return route==='voA'?'VO A · documental':route==='voB'?'VO B · cine':route==='source'?'Entrevista original':route==='final'?'Montaje final':route}
function catalog(kind,id){const extKey=kind==='xr'?'xrDefinitions':kind==='sfx'?'sfxDefinitions':null;const ext=extKey?(state.project.extensions?.[extKey]||[]):[];const hitExt=ext.find(x=>String(x.id)===String(id));if(hitExt)return clone(hitExt);const rows=state.project.catalogSnapshot?.[kind]||[];return rows.find(x=>String(x.id)===String(id))||{id,name:`Custom ${id}`,kind:'custom',fallback:true,description:'Definición personalizada/no registrada. El Lienzo conserva todos los datos.'}}
function createXRDefinition(def){if(!def?.id)throw new Error('XR definition requires id');state.project.extensions=state.project.extensions||{};state.project.extensions.xrDefinitions=state.project.extensions.xrDefinitions||[];const before=JSON.stringify(state.project),normalized={...clone(def),fallback:false},i=state.project.extensions.xrDefinitions.findIndex(x=>x.id===def.id);if(i>=0)state.project.extensions.xrDefinitions[i]=normalized;else state.project.extensions.xrDefinitions.push(normalized);checkpoint('Definición XR',before);return clone(normalized)}
function createSFXDefinition(def){if(!def?.id)throw new Error('SFX definition requires id');state.project.extensions=state.project.extensions||{};state.project.extensions.sfxDefinitions=state.project.extensions.sfxDefinitions||[];const before=JSON.stringify(state.project),normalized={...clone(def),fallback:false},i=state.project.extensions.sfxDefinitions.findIndex(x=>x.id===def.id);if(i>=0)state.project.extensions.sfxDefinitions[i]=normalized;else state.project.extensions.sfxDefinitions.push(normalized);checkpoint('Definición SFX',before);return clone(normalized)}
function mergeIdentity(x){if(!x||typeof x!=='object'||Array.isArray(x))return null;for(const k of ['canonicalId','contentId','content_id','uid','id','itemId','assetId','stateId','partId'])if(clean(x[k]))return `${k}:${clean(x[k])}`;return null}
function sameValue(a,b){return JSON.stringify(a)===JSON.stringify(b)}
function mergeCopy(x){return x===undefined?undefined:clone(x)}
function mergeValue(baseValue,localValue,remoteValue,path,conflicts){
 if(sameValue(localValue,remoteValue))return mergeCopy(localValue);
 if(sameValue(localValue,baseValue))return mergeCopy(remoteValue);
 if(sameValue(remoteValue,baseValue))return mergeCopy(localValue);
 const objectLike=x=>x&&typeof x==='object'&&!Array.isArray(x);
 if(objectLike(baseValue)&&objectLike(localValue)&&objectLike(remoteValue)){
   const out={},keys=new Set([...Object.keys(baseValue),...Object.keys(localValue),...Object.keys(remoteValue)]);
   for(const key of keys)out[key]=mergeValue(baseValue[key],localValue[key],remoteValue[key],path.concat(key),conflicts);
   return out;
 }
 if(Array.isArray(baseValue)&&Array.isArray(localValue)&&Array.isArray(remoteValue)){
   const all=[...baseValue,...localValue,...remoteValue],keyed=all.length&&all.every(x=>mergeIdentity(x));
   if(keyed){
     const bm=new Map(baseValue.map(x=>[mergeIdentity(x),x])),lm=new Map(localValue.map(x=>[mergeIdentity(x),x])),rm=new Map(remoteValue.map(x=>[mergeIdentity(x),x])),order=[];
     for(const x of all){const key=mergeIdentity(x);if(!order.includes(key))order.push(key)}
     return order.map((key,index)=>mergeValue(bm.get(key),lm.get(key),rm.get(key),path.concat(index),conflicts)).filter(x=>x!==undefined);
   }
 }
 const conflict={path:[...path],pathLabel:path.join('.'),base:mergeCopy(baseValue),local:mergeCopy(localValue),remote:mergeCopy(remoteValue),choice:'local'};
 conflicts.push(conflict);
 return mergeCopy(localValue);
}
function mergeProjects(baseDoc,localDoc,remoteDoc){const conflicts=[],merged=mergeValue(baseDoc,localDoc,remoteDoc,[],conflicts);return {merged,conflicts}}
function setMergePath(obj,path,value){if(!path.length)return value;let cur=obj;for(let i=0;i<path.length-1;i++){const key=path[i];if(cur[key]===undefined||cur[key]===null)cur[key]=typeof path[i+1]==='number'?[]:{};cur=cur[key]}cur[path[path.length-1]]=mergeCopy(value);return obj}
function parseMergeDocument(text){const raw=String(text||'').trim();if(raw.startsWith('<')){const doc=new DOMParser().parseFromString(raw,'text/html'),script=doc.querySelector('#app-data');if(!script)throw new Error('El HTML no contiene #app-data');return JSON.parse(script.textContent||'{}')}const obj=JSON.parse(raw);return obj?.project&&obj.schemaVersion==='abrxos.update.v3'?obj.project:obj}
function openMergeDialog(){const dialog=$('#merge-dialog'),root=$('#merge-content');root.innerHTML=`<header class="merge-head"><div><small>LOCAL / REMOTE / BASE</small><h2>Fusionar otra revisión</h2></div><button data-action="close-merge">×</button></header><p class="merge-help">BASE es la revisión de partida. LOCAL conserva tus cambios de este dispositivo. Carga otro Lienzo/JSON como REMOTE; sólo los campos modificados por ambos lados de forma distinta requieren decisión.</p><div class="merge-sources"><div><b>BASE</b><small>${esc(state.mergeBase?.revision?.id||'embedded')}</small></div><div><b>LOCAL</b><small>${esc(state.project?.revision?.id||'actual')}</small></div><label><b>REMOTE</b><input id="merge-file" type="file" accept=".html,.htm,.json"></label></div><div id="merge-results"></div>`;root.querySelector('[data-action="close-merge"]').onclick=()=>dialog.close();root.querySelector('#merge-file').onchange=loadMergeRemote;dialog.showModal()}
async function loadMergeRemote(ev){const file=ev.target.files?.[0],root=$('#merge-results');if(!file)return;try{const remote=parseMergeDocument(await file.text()),session=mergeProjects(state.mergeBase||base,state.project,remote);state.mergeSession=session;root.innerHTML=`<div class="merge-summary"><b>${session.conflicts.length?`${session.conflicts.length} conflictos requieren decisión`:'Merge automático sin conflictos'}</b></div>${session.conflicts.map((c,i)=>`<section class="merge-conflict"><code>${esc(c.pathLabel||'(raíz)')}</code><div class="merge-choices"><label><input type="radio" name="merge-${i}" value="local" checked> LOCAL<pre>${esc(JSON.stringify(c.local,null,2))}</pre></label><label><input type="radio" name="merge-${i}" value="remote"> REMOTE<pre>${esc(JSON.stringify(c.remote,null,2))}</pre></label></div></section>`).join('')}<div class="merge-actions"><button data-action="apply-merge" class="primary">Aplicar merge</button></div>`;root.querySelector('[data-action="apply-merge"]').onclick=applyMergeSession}catch(err){root.innerHTML=`<div class="empty">No pude leer REMOTE: ${esc(err.message||err)}</div>`}}
function applyMergeSession(){const session=state.mergeSession;if(!session)return;const before=JSON.stringify(state.project),merged=clone(session.merged);session.conflicts.forEach((c,i)=>{const choice=document.querySelector(`input[name="merge-${i}"]:checked`)?.value||'local';if(choice==='remote')setMergePath(merged,c.path,c.remote)});state.project=merged;state.mergeBase=clone(merged);state.mergeSession=null;checkpoint('Merge LOCAL/REMOTE/BASE',before);$('#merge-dialog')?.close();render();toast('Merge aplicado')}
function schedule(p){if(!p.schedule||typeof p.schedule!=='object')p.schedule={date:'',time:'',platforms:[]};return p.schedule}
function saveLocal(){try{localStorage.setItem(`abrxos:v3:${state.project.projectId}:${state.project.canvas?.title||'canvas'}`,JSON.stringify(state.project))}catch(e){}}
function restoreLocal(){try{const raw=localStorage.getItem(`abrxos:v3:${state.project.projectId}:${state.project.canvas?.title||'canvas'}`);if(raw){const x=JSON.parse(raw);if(x?.schemaVersion==='abrxos.document.v3')state.project=x}}catch(e){}}
function checkpoint(label,before){state.history.undo.push({label,json:before||JSON.stringify(state.project),piece:state.selectedPieceId,event:state.selectedEventId});if(state.history.undo.length>80)state.history.undo.shift();state.history.redo=[];updateHistoryButtons();saveLocal()}
function undo(){const x=state.history.undo.pop();if(!x)return;state.history.redo.push({label:x.label,json:JSON.stringify(state.project),piece:state.selectedPieceId,event:state.selectedEventId});state.project=JSON.parse(x.json);state.selectedPieceId=x.piece;state.selectedEventId=x.event;render();updateHistoryButtons();saveLocal()}
function redo(){const x=state.history.redo.pop();if(!x)return;state.history.undo.push({label:x.label,json:JSON.stringify(state.project),piece:state.selectedPieceId,event:state.selectedEventId});state.project=JSON.parse(x.json);state.selectedPieceId=x.piece;state.selectedEventId=x.event;render();updateHistoryButtons();saveLocal()}
function updateHistoryButtons(){$('[data-action="undo"]')?.toggleAttribute('disabled',!state.history.undo.length);$('[data-action="redo"]')?.toggleAttribute('disabled',!state.history.redo.length)}
function copyText(text){navigator.clipboard?.writeText(String(text??'')).catch(()=>{});toast('Copiado')}
function toast(text){let t=$('#toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent=text;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1800)}
function setScheduleDate(id,date){const p=getPiece(id);if(!p)return;const before=JSON.stringify(state.project);schedule(p).date=date||'';if(date&&p.workflowStatus==='LISTO')p.workflowStatus='PROGRAMADO';if(!date&&p.workflowStatus==='PROGRAMADO')p.workflowStatus='LISTO';checkpoint('Calendario',before);renderCalendar();renderSidebar()}

function shell(){
 const rendererName=esc(state.project.renderer?.name||state.renderer);
 $('#app').innerHTML=`<header class="topbar"><button class="iconbtn" data-action="sidebar">☰</button><div class="brand"><b>ABRXOS</b><span>${rendererName} · ${esc(state.project.canvas?.title||state.project.title||state.project.projectId)}</span></div><nav class="viewtabs"><button data-view="editor">Editor</button><button data-view="calendar">Calendario</button><button data-view="kanban">Kanban</button></nav><div class="grow"></div><button data-action="undo">↶</button><button data-action="redo">↷</button><button data-action="merge">Merge</button><button data-action="export-json">JSON</button><button class="primary" data-action="export-html">Exportar HTML</button></header><div class="shell"><aside id="sidebar" class="sidebar"><div class="sidehead"><b>Fichas</b></div><input id="pieceSearch" placeholder="Buscar…"><div id="pieceList" class="piece-list"></div></aside><main id="main" class="main"></main></div><dialog class="merge-dialog" id="merge-dialog"><div id="merge-content"></div></dialog><div id="toast" class="toast"></div>`;
 $$('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;renderMain()});
 $('[data-action="undo"]').onclick=undo;$('[data-action="redo"]').onclick=redo;$('[data-action="merge"]').onclick=openMergeDialog;
 $('[data-action="export-json"]').onclick=exportJSON;$('[data-action="export-html"]').onclick=exportHTML;
 $('[data-action="sidebar"]').onclick=()=>$('#app').classList.toggle('sidebar-open');
 $('#pieceSearch').oninput=renderSidebar;
}
function renderSidebar(){const q=clean($('#pieceSearch')?.value).toLowerCase();const list=$('#pieceList');if(!list)return;list.innerHTML=pieces().filter(p=>!q||(clean(p.title)+' '+pid(p)).toLowerCase().includes(q)).map(p=>`<button class="piece-row ${pid(p)===state.selectedPieceId?'active':''}" data-piece-id="${esc(pid(p))}"><span class="piece-code">${esc(pid(p).slice(0,8))}</span><span><b>${esc(p.title||pid(p))}</b><small>${esc(ptype(p))} · ${esc(p.stage||'BETA')} · ${esc(p.workflowStatus||'PENDIENTE')}</small></span></button>`).join('');$$('[data-piece-id]').forEach(b=>b.onclick=()=>{state.selectedPieceId=b.dataset.pieceId;state.selectedEventId=null;state.selectedStaticId=null;state.view='editor';render()})}
function renderMain(){const main=$('#main');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));if(state.view==='calendar')renderCalendar();else if(state.view==='kanban')renderKanban();else renderEditor()}
function render(){if(!$('#main'))shell();renderSidebar();renderMain();updateHistoryButtons()}

function renderEditor(){const p=currentPiece(),main=$('#main');if(!p){main.innerHTML='<div class="empty">Sin fichas.</div>';return}if(VIDEO.has(ptype(p)))renderVideo(p);else renderStatic(p)}
function renderVideo(p){const d=duration(p),routes=availableRoutes(p),route=currentRoute(p),routeControl=routes.length>1?`<select id="route-select" aria-label="Ruta editorial">${routes.map(r=>`<option value="${esc(r)}" ${r===route?'selected':''}>${esc(routeLabel(r))}</option>`).join('')}</select>`:'';$('#main').innerHTML=`<section class="editor-workspace"><header class="piecehead"><div><h1>${esc(p.title||pid(p))}</h1><small>${esc(pid(p))} · ${esc(ptype(p))} · ${d.toFixed(2)} s</small></div><div class="pieceactions">${routeControl}<button data-action="add-xr">+ XR</button><button data-action="add-sfx">+ SFX</button><button data-action="copy-piece">Copiar ficha</button></div></header><div class="editor-upper"><section class="story-panel">${renderStory(p)}</section><section class="inspector-panel"><div id="inspector"></div></section></div><section class="timeline-panel"><div class="timeline-tools"><b>Timeline T1–T9</b><span>${d.toFixed(2)} s</span><button data-action="zoom-out">−</button><button data-action="fit">Ajustar</button><button data-action="zoom-in">+</button></div><div id="timeline-root"></div></section></section>`;
 const routeSelect=$('#route-select');if(routeSelect)routeSelect.onchange=()=>{state.routeByPiece[pid(p)]=routeSelect.value;const visibleIds=new Set(routeEvents(p).map(e=>e.id));if(state.selectedEventId&&!visibleIds.has(state.selectedEventId))state.selectedEventId=null;renderVideo(p)};
 $('[data-action="copy-piece"]').onclick=()=>copyText(JSON.stringify(p,null,2));$('[data-action="add-xr"]').onclick=()=>addXR(p);$('[data-action="add-sfx"]').onclick=()=>addSFX(p);$('[data-action="zoom-in"]').onclick=()=>{state.scale=Math.min(80,state.scale*1.25);renderTimeline(p)};$('[data-action="zoom-out"]').onclick=()=>{state.scale=Math.max(4,state.scale/1.25);renderTimeline(p)};$('[data-action="fit"]').onclick=()=>{state.scale=Math.max(4,($('#timeline-root').clientWidth-120)/duration(p));renderTimeline(p)};renderInspector();renderTimeline(p)}
function renderStory(p){const route=currentRoute(p),script=p.storyScripts&&Array.isArray(p.storyScripts[route])?p.storyScripts[route]:null,parts=script||p.parts||[];if(!parts.length)return `<div class="storyhead"><b>Historia / Partes · ${esc(routeLabel(route))}</b></div><div class="empty">Sin partes estructuradas.</div>`;return `<div class="storyhead"><b>Historia / Partes · ${esc(routeLabel(route))}</b></div>${parts.map(x=>`<article class="story-item"><small>${esc(x.role||x.partId||x.kind||'PARTE')}</small><p>${esc(x.displayText||x.text||x.literalText||'')}</p></article>`).join('')}`}
function renderTimeline(p){const root=$('#timeline-root');if(!root)return;const d=duration(p),w=Math.max(900,d*state.scale+40),visible=routeEvents(p);let ruler='';const step=d>120?20:d>60?10:5;for(let t=0;t<=d;t+=step)ruler+=`<span style="left:${t*state.scale}px">${fmt(t)}</span>`;let html=`<div class="timeline-grid" style="width:${w+92}px"><div class="ruler-row"><div></div><div class="ruler" style="width:${w}px">${ruler}</div></div>`;for(const tr of TRACKS){const ev=visible.filter(e=>e?.track===tr);html+=`<div class="track-row"><div class="track-label">${TRACK_LABELS[tr]}</div><div class="lane" data-track="${tr}" style="width:${w}px">`;for(const e of ev){const st=+e.start||0,en=Math.max(st+.04,+e.end||st+.04),left=st*state.scale,width=Math.max(6,(en-st)*state.scale);html+=`<button class="time-block track-${tr} ${e.id===state.selectedEventId?'active':''}" data-event-id="${esc(e.id)}" data-track="${tr}" style="left:${left}px;width:${width}px"><span class="handle left" data-handle="left"></span><b>${esc(e.label||e.text||e.id)}</b><small>${st.toFixed(2)}–${en.toFixed(2)}</small><span class="handle right" data-handle="right"></span></button>`}html+='</div></div>'}html+='</div>';root.innerHTML=html;bindTimeline(p)}
function bindTimeline(p){$$('.time-block').forEach(block=>{block.onpointerdown=e=>timelinePointerDown(e,p,block);block.onclick=e=>{if(Date.now()<state.suppressClickUntil)return;selectEvent(block.dataset.eventId)};block.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectEvent(block.dataset.eventId)}}})}
function selectEvent(id){state.selectedEventId=id;renderInspector();const p=currentPiece();if(p&&VIDEO.has(ptype(p)))renderTimeline(p)}
function recordCutOverride(p,e){if(!p||!e?.editorialOverride)return;p.cutOverrides=p.cutOverrides||[];const row={eventId:e.id,partId:e.partId||null,sourceRangeRef:e.sourceRangeId||e.sourceRangeRef||e.partId||null,originalTimeline:{start:+e.editorialOverride.originalStart||0,end:+e.editorialOverride.originalEnd||0},editorialTimeline:{start:+e.start||0,end:+e.end||0},reason:e.editorialOverride.reason||'timeline_edit',status:'needs_review',sourceTruthUnchanged:true};const i=p.cutOverrides.findIndex(x=>x.eventId===e.id);if(i>=0)p.cutOverrides[i]=row;else p.cutOverrides.push(row)}
function timelinePointerDown(ev,p,block){if(ev.button!==0)return;const event=(p.timeline||[]).find(x=>x.id===block.dataset.eventId);if(!event)return;const handle=ev.target.dataset.handle||'move',threshold=ev.pointerType==='touch'?10:6,startX=ev.clientX,startY=ev.clientY,origStart=+event.start||0,origEnd=+event.end||origStart+.1;const children=(p.timeline||[]).filter(x=>x.parentId===event.id&&x.timingMode==='follow_parent').map(x=>({x,st:+x.start||0,en:+x.end||0}));const before=JSON.stringify(state.project);state.gesture={eventId:event.id,before,started:false};block.setPointerCapture?.(ev.pointerId);function move(me){const dist=Math.hypot(me.clientX-startX,me.clientY-startY);if(!state.gesture?.started){if(dist<threshold)return;state.gesture.started=true;if(event.timingMode==='locked_to_source'){event.editorialOverride=event.editorialOverride||{originalStart:origStart,originalEnd:origEnd,reason:handle==='move'?'timeline_drag':'timeline_trim',requiresReview:true};event.timingMode='manual_review'}}const dt=(me.clientX-startX)/state.scale;if(handle==='move'){const dur=origEnd-origStart;event.start=round3(Math.max(0,origStart+dt));event.end=round3(event.start+dur);const shift=event.start-origStart;for(const c of children){c.x.start=round3(Math.max(0,c.st+shift));c.x.end=round3(Math.max(c.x.start+.04,c.en+shift))}}else if(handle==='left'){event.start=round3(clamp(origStart+dt,0,origEnd-.04));const od=Math.max(.04,origEnd-origStart),nd=Math.max(.04,event.end-event.start);for(const c of children){const rs=(c.st-origStart)/od,re=(c.en-origStart)/od;c.x.start=round3(event.start+rs*nd);c.x.end=round3(event.start+re*nd)}}else{event.end=round3(Math.max(origStart+.04,origEnd+dt));const od=Math.max(.04,origEnd-origStart),nd=Math.max(.04,event.end-event.start);for(const c of children){const rs=(c.st-origStart)/od,re=(c.en-origStart)/od;c.x.start=round3(event.start+rs*nd);c.x.end=round3(event.start+re*nd)}}renderTimeline(p)}function finish(){window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',cancel);window.removeEventListener('keydown',key);const g=state.gesture;state.gesture=null;return g}function up(){const g=finish();if(!g?.started){selectEvent(event.id);return}state.selectedEventId=event.id;state.suppressClickUntil=Date.now()+180;if(event.editorialOverride)recordCutOverride(p,event);checkpoint(handle==='move'?'Mover timeline':'Trim timeline',before);renderInspector();renderTimeline(p)}function cancel(){finish();state.project=JSON.parse(before);render()}function key(k){if(k.key==='Escape'){k.preventDefault();cancel()}}window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true});window.addEventListener('pointercancel',cancel,{once:true});window.addEventListener('keydown',key);ev.preventDefault()}

function renderInspector(){const root=$('#inspector');if(!root)return;const p=currentPiece(),e=currentEvent();if(!p){root.innerHTML='';return}if(!e){root.innerHTML=`<div class="inspector-head"><h2>${esc(p.title||pid(p))}</h2><button data-copy="piece">Copiar</button></div><div class="info-card"><small>TESIS / OBJETIVO</small><p>${esc(p.thesis||p.objective||'Selecciona un bloque del timeline para inspeccionarlo.')}</p></div><details class="raw"><summary>JSON avanzado</summary><textarea id="raw-json">${esc(JSON.stringify(p,null,2))}</textarea></details>`;root.querySelector('[data-copy]')?.addEventListener('click',()=>copyText(JSON.stringify(p,null,2)));return}
 const def=e.track==='xr'?catalog('xr',e.definitionId||e.xrFamily||e.xrType||'CUSTOM'):e.track==='sfx'?catalog('sfx',e.definitionId||e.sfx?.definitionId||'CUSTOM'):null;
 let body=`<div class="inspector-head"><div><small>${esc(e.track||e.type||'EVENTO')} ${def?`· ${esc(def.id)}`:''}</small><h2>${esc(e.label||e.id)}</h2></div><button data-copy="event">Copiar</button></div><div class="meta-pills"><span>${(+e.start||0).toFixed(3)}</span><span>${(+e.end||0).toFixed(3)}</span><span>${esc(e.timingMode||'free')}</span></div>`;
 if(def)body+=`<div class="info-card"><small>DEFINICIÓN</small><b>${esc(def.name)}</b><p>${esc(def.description||'')}</p></div>`;
 if(e.function)body+=card('FUNCIÓN NARRATIVA',e.function,true);
 if(e.text||e.displayText)body+=card('TEXTO',e.text||e.displayText,true);
 if(e.track==='captions')body+=renderCaptionDetails(e);
 if(e.track==='xr')body+=renderXRDetails(e);
 else if(e.track==='images')body+=renderImageDetails(e);
 else if(e.track==='sfx')body+=renderSFXDetails(e);
 else if(e.track==='motion')body+=card('MOTION',e.instructions||e.description||JSON.stringify(e.keyframes||[],null,2),true);
 body+=`<div class="edit-grid"><label>Inicio<input id="event-start" type="number" step="0.001" value="${+e.start||0}"></label><label>Final<input id="event-end" type="number" step="0.001" value="${+e.end||0}"></label></div><details class="raw"><summary>JSON avanzado</summary><textarea id="raw-json">${esc(JSON.stringify(e,null,2))}</textarea><button data-action="apply-raw">Aplicar JSON</button></details>`;
 root.innerHTML=body;root.querySelector('[data-copy="event"]').onclick=()=>copyText(JSON.stringify(e,null,2));$$('[data-copy]',root).filter(x=>x.dataset.copy!=='event').forEach(b=>b.onclick=()=>copyText(b.dataset.value||''));
 const st=$('#event-start'),en=$('#event-end');st.onchange=()=>editEventTime(e,+st.value,+e.end,'Editar tiempo');en.onchange=()=>editEventTime(e,+e.start,+en.value,'Editar tiempo');const saveDetails=root.querySelector('[data-action="save-event-details"]');if(saveDetails)saveDetails.onclick=()=>{const before=JSON.stringify(state.project);if(e.track==='xr'){e.function=$('#xr-function-edit')?.value??e.function;for(const a of e.assets||[]){const aid=a.assetId||a.localId||'ASSET',desc=root.querySelector(`[data-asset-description="${CSS.escape(aid)}"]`),prompt=root.querySelector(`[data-asset-prompt="${CSS.escape(aid)}"]`);if(desc){a.description=desc.value;a.shortDescription=desc.value;syncAssetField(aid,'description',desc.value);syncAssetField(aid,'shortDescription',desc.value)}if(prompt){a.prompt=prompt.value;a.promptNoText=prompt.value;syncAssetField(aid,'prompt',prompt.value);syncAssetField(aid,'promptNoText',prompt.value)}}}else if(e.track==='images'){const a=e.asset||e,aid=assetKey(a),desc=$('#image-description-edit')?.value??'',prompt=$('#image-prompt-edit')?.value??'';a.description=desc;a.prompt=prompt;a.promptNoText=prompt;if(aid){syncAssetField(aid,'description',desc);syncAssetField(aid,'prompt',prompt);syncAssetField(aid,'promptNoText',prompt)}}else if(e.track==='sfx'){const sx=e.sfx||(e.sfx={});sx.search=$('#sfx-search-edit')?.value??sx.search;sx.trigger=$('#sfx-trigger-edit')?.value??sx.trigger;sx.mix=$('#sfx-mix-edit')?.value??sx.mix}else if(e.track==='captions'){const text=$('#caption-text-edit')?.value??e.text,highlight=$('#caption-highlight-edit')?.value??e.highlightWord;e.text=text;e.displayText=text;e.label=text;e.highlightWord=highlight;e.highlightStatus=highlight?'confirmed':'suggested';e.displayMode=$('#caption-mode-edit')?.value||'normal';e.wordCount=clean(text).split(/\s+/).filter(Boolean).length}checkpoint('Editar información interna',before);render();toast('Información actualizada')};root.querySelector('[data-action="apply-raw"]').onclick=()=>{try{const parsed=JSON.parse($('#raw-json').value),before=JSON.stringify(state.project),idx=(p.timeline||[]).findIndex(x=>x.id===e.id);if(idx<0)return;p.timeline[idx]=parsed;state.selectedEventId=parsed.id||e.id;checkpoint('Editar JSON',before);render()}catch(err){toast('JSON inválido')}}}
function card(title,text,copy=false){return `<div class="info-card"><div class="cardhead"><small>${esc(title)}</small>${copy?`<button data-copy="text" data-value="${esc(text)}">Copiar</button>`:''}</div><p>${esc(text||'—')}</p></div>`}
function renderXRDetails(e){let h=`<h3>Editar XR</h3><label class="field-block">Función narrativa<textarea id="xr-function-edit">${esc(e.function||'')}</textarea></label><h3>Estados internos</h3>`;for(const s of e.states||[])h+=`<div class="nested-card"><b>${esc(s.stateId||'STATE')}</b><small>${(+s.start||0).toFixed(2)}–${(+s.end||0).toFixed(2)}</small><p>${esc(s.description||s.shortDescription||'')}</p></div>`;h+='<h3>Assets</h3>';for(const a of e.assets||[]){const aid=a.assetId||a.localId||'ASSET';h+=`<div class="nested-card"><div class="cardhead"><b>${esc(a.localId||a.assetId||'ASSET')}</b><button data-copy="prompt" data-value="${esc(a.prompt||a.promptNoText||'')}">Copiar prompt</button></div><p>${esc(a.description||a.shortDescription||'')}</p><pre>${esc(a.prompt||a.promptNoText||'')}</pre><label class="field-block">Descripción<textarea data-asset-description="${esc(aid)}">${esc(a.description||a.shortDescription||'')}</textarea></label><label class="field-block">Prompt<textarea data-asset-prompt="${esc(aid)}">${esc(a.prompt||a.promptNoText||'')}</textarea></label><small>${esc(a.status||'')}</small></div>`}h+=`<button class="primary inspector-save" data-action="save-event-details">Guardar cambios de XR</button>`;return h}
function renderImageDetails(e){const a=e.asset||e;return card('DESCRIPCIÓN',a.description||e.imageDescription||'',true)+card('PROMPT',a.prompt||a.promptNoText||e.prompt||'',true)+`<h3>Editar imagen</h3><label class="field-block">Descripción<textarea id="image-description-edit">${esc(a.description||e.imageDescription||'')}</textarea></label><label class="field-block">Prompt<textarea id="image-prompt-edit">${esc(a.prompt||a.promptNoText||e.prompt||'')}</textarea></label><button class="primary inspector-save" data-action="save-event-details">Guardar imagen</button>`}
function renderSFXDetails(e){const s=e.sfx||e;return card('BÚSQUEDA',s.search||'',true)+card('TRIGGER',s.trigger||'')+card('MEZCLA',s.mix||s.defaultLevel||'')+`<h3>Editar SFX</h3><label class="field-block">Búsqueda<input id="sfx-search-edit" value="${esc(s.search||'')}"></label><label class="field-block">Trigger<textarea id="sfx-trigger-edit">${esc(s.trigger||'')}</textarea></label><label class="field-block">Mezcla<input id="sfx-mix-edit" value="${esc(s.mix||s.defaultLevel||'')}"></label><button class="primary inspector-save" data-action="save-event-details">Guardar SFX</button>`}
function renderCaptionDetails(e){return `<h3>Editar caption</h3><label class="field-block">Frase<textarea id="caption-text-edit">${esc(e.text||e.displayText||'')}</textarea></label><label class="field-block">Palabra destacada<input id="caption-highlight-edit" value="${esc(e.highlightWord||'')}"></label><label class="field-block">Modo<select id="caption-mode-edit"><option value="normal" ${(e.displayMode||'normal')==='normal'?'selected':''}>Frase normal</option><option value="hero_word" ${e.displayMode==='hero_word'?'selected':''}>Palabra protagonista</option></select></label><button class="primary inspector-save" data-action="save-event-details">Guardar caption</button>`}
function editEventTime(e,start,end,label){if(!(Number.isFinite(start)&&Number.isFinite(end)&&end>start)){toast('Rango inválido');renderInspector();return}const before=JSON.stringify(state.project);if(e.timingMode==='locked_to_source'){e.editorialOverride=e.editorialOverride||{originalStart:+e.start||0,originalEnd:+e.end||0,reason:'manual_edit',requiresReview:true};e.timingMode='manual_review'}e.start=round3(Math.max(0,start));e.end=round3(end);if(e.editorialOverride)recordCutOverride(currentPiece(),e);checkpoint(label,before);render()}

function renderStatic(p){
 const items=p.staticProduction?.items||[];
 if(!state.selectedStaticId&&items[0])state.selectedStaticId=items[0].itemId||items[0].id;
 const x=items.find(z=>(z.itemId||z.id)===state.selectedStaticId)||items[0];
 if(!x){$('#main').innerHTML='<div class="empty">Sin slides/bloques estáticos.</div>';return}
 const visual=(x.visual&&typeof x.visual==='object')?x.visual:(x.visual={description:clean(x.visual)});
 $('#main').innerHTML=`<section class="carousel-workspace"><header class="piecehead"><div><h1>${esc(p.title||pid(p))}</h1><small>${items.length} slides · ${esc(p.stage||'BETA')}</small></div><button data-action="copy-piece">Copiar ficha</button></header><div class="carousel-grid"><aside class="slides-list">${items.map((s,i)=>`<button class="carousel-slide-card ${(s.itemId||s.id)===state.selectedStaticId?'active':''}" data-slide-id="${esc(s.itemId||s.id)}"><small>${String(i+1).padStart(2,'0')} · ${esc(s.function||'SLIDE')}</small><b>${esc(s.headline||s.title||'')}</b></button>`).join('')}</aside><section class="slide-preview"><div class="preview-card"><small>${esc(x.function||'SLIDE')}</small><h2>${esc(x.headline||x.title||'')}</h2><p>${esc(x.body||x.text||'')}</p><hr><small>${esc(visual.description||'')}</small></div></section><aside class="static-inspector"><div class="cardhead"><h2>${esc(x.headline||x.title||'Slide')}</h2><button data-action="copy-static">Copiar slide</button></div><label class="field-block">Titular<textarea id="static-headline-edit">${esc(x.headline||x.title||'')}</textarea></label><label class="field-block">Cuerpo<textarea id="static-body-edit">${esc(x.body||x.text||'')}</textarea></label><label class="field-block">Dirección visual<textarea id="static-visual-edit">${esc(visual.description||'')}</textarea></label><label class="field-block">Prompt<textarea id="static-prompt-edit">${esc(visual.prompt||visual.promptNoText||'')}</textarea></label><button class="primary inspector-save" data-action="save-static-details">Guardar slide</button>${card('COPY / PUBLICACIÓN',typeof p.staticProduction?.copy==='string'?p.staticProduction.copy:(p.staticProduction?.copy?.text||p.staticProduction?.copy?.caption||''),true)}</aside></div></section>`;
 $('[data-action="copy-piece"]').onclick=()=>copyText(JSON.stringify(p,null,2));
 $('[data-action="copy-static"]').onclick=()=>copyText(JSON.stringify(x,null,2));
 $$('[data-slide-id]').forEach(b=>b.onclick=()=>{state.selectedStaticId=b.dataset.slideId;renderStatic(p)});
 $('[data-action="save-static-details"]').onclick=()=>{const before=JSON.stringify(state.project),headline=$('#static-headline-edit').value,body=$('#static-body-edit').value,description=$('#static-visual-edit').value,prompt=$('#static-prompt-edit').value;x.headline=headline;x.title=headline;x.body=body;x.text=[headline,body].filter(Boolean).join('\n\n');visual.description=description;visual.prompt=prompt;visual.promptNoText=prompt;checkpoint('Editar slide',before);renderStatic(p);toast('Slide actualizado')};
 $$('[data-copy]', $('.static-inspector')).forEach(b=>b.onclick=()=>copyText(b.dataset.value||''));
}

function renderCalendar(){const main=$('#main'),d=new Date(state.calendar.getFullYear(),state.calendar.getMonth(),1),first=(d.getDay()+6)%7,start=new Date(d);start.setDate(1-first);let days='';for(let i=0;i<42;i++){const day=new Date(start);day.setDate(start.getDate()+i);const key=`${day.getFullYear()}-${String(day.getMonth()+1).padStart(2,'0')}-${String(day.getDate()).padStart(2,'0')}`,rows=pieces().filter(p=>schedule(p).date===key);days+=`<div class="calendar-day" data-date="${key}"><small>${day.getDate()}</small>${rows.map(p=>`<button draggable="true" data-calendar-piece="${esc(pid(p))}">${esc(p.title||pid(p))}</button>`).join('')}</div>`}const uns=pieces().filter(p=>!schedule(p).date);main.innerHTML=`<section class="calendar-workspace"><header class="viewhead"><h1>Calendario</h1><div><button data-action="prev-month">‹</button><b>${d.toLocaleString('es',{month:'long',year:'numeric'})}</b><button data-action="next-month">›</button></div></header><div class="calendar-layout"><div class="calendar-grid">${days}</div><aside class="unscheduled"><h2>Sin programar</h2><div id="unscheduled-list">${uns.map(p=>`<button draggable="true" data-calendar-piece="${esc(pid(p))}">${esc(p.title||pid(p))}</button>`).join('')}</div></aside></div></section>`;$('[data-action="prev-month"]').onclick=()=>{state.calendar=new Date(d.getFullYear(),d.getMonth()-1,1);renderCalendar()};$('[data-action="next-month"]').onclick=()=>{state.calendar=new Date(d.getFullYear(),d.getMonth()+1,1);renderCalendar()};bindCalendarDnD()}
function bindCalendarDnD(){$$('[data-calendar-piece]').forEach(b=>b.ondragstart=e=>e.dataTransfer.setData('text/plain',b.dataset.calendarPiece));$$('.calendar-day').forEach(c=>{c.ondragover=e=>e.preventDefault();c.ondrop=e=>{e.preventDefault();setScheduleDate(e.dataTransfer.getData('text/plain'),c.dataset.date)}});const u=$('.unscheduled');if(u){u.ondragover=e=>e.preventDefault();u.ondrop=e=>{e.preventDefault();setScheduleDate(e.dataTransfer.getData('text/plain'),'')}}}
function renderKanban(){const main=$('#main');main.innerHTML=`<section class="kanban-workspace"><header class="viewhead"><h1>Kanban</h1></header><div class="kanban-grid">${WORKFLOW.map(w=>`<section class="kanban-col" data-workflow="${w}"><h3>${w}</h3>${pieces().filter(p=>(p.workflowStatus||'PENDIENTE')===w).map(p=>`<button draggable="true" data-kanban-piece="${esc(pid(p))}"><b>${esc(p.title||pid(p))}</b><small>${esc(ptype(p))}</small></button>`).join('')}</section>`).join('')}</div></section>`;$$('[data-kanban-piece]').forEach(b=>b.ondragstart=e=>e.dataTransfer.setData('text/plain',b.dataset.kanbanPiece));$$('[data-workflow]').forEach(c=>{c.ondragover=e=>e.preventDefault();c.ondrop=e=>{e.preventDefault();const p=getPiece(e.dataTransfer.getData('text/plain'));if(!p)return;const before=JSON.stringify(state.project);p.workflowStatus=c.dataset.workflow;checkpoint('Kanban',before);renderKanban();renderSidebar()}})}

function addXR(p){const chosen=prompt('XR ID (XR00…XR09 o nuevo ID):','XR06');if(!chosen)return;let def=catalog('xr',chosen);if(def.fallback){const name=prompt('Nombre de este nuevo XR:',`Custom ${chosen}`);if(!name)return;createXRDefinition({id:chosen,name,kind:'custom',defaultAssets:1,description:'Definición creada desde el Lienzo; completar reglas visuales cuando corresponda.'});def=catalog('xr',chosen)}const st=Number(prompt('Inicio en segundos:','0'));const en=Number(prompt('Final en segundos:','5'));if(!(en>st))return;const before=JSON.stringify(state.project),id=`${pid(p)}_${chosen}_${Date.now().toString().slice(-6)}`,count=Math.max(1,+def.defaultAssets||1),assets=[];for(let i=0;i<count;i++)assets.push({assetId:`${id}_A${String(i+1).padStart(2,'0')}`,localId:`A${String(i+1).padStart(2,'0')}`,description:'Pendiente de definir',prompt:'',status:'pending_creation'});p.timeline=p.timeline||[];const routes=availableRoutes(p);p.timeline.push({id,track:'xr',type:'xr',definitionId:chosen,xrFamily:chosen,label:def.name||chosen,start:st,end:en,function:'Pendiente de definir',states:[],assets,timingMode:'free',...(routes.length>1?{routes:[currentRoute(p)]}:{})});checkpoint('Crear XR',before);state.selectedEventId=id;render()}
function addSFX(p){const chosen=prompt('SFX ID de biblioteca o custom:','SFX_HIT_SOFT_01');if(!chosen)return;let def=catalog('sfx',chosen);if(def.fallback){const name=prompt('Nombre de este nuevo SFX:',`Custom ${chosen}`);if(!name)return;createSFXDefinition({id:chosen,name,kind:'custom',duration:.2,search:'',purpose:'Pendiente de definir',defaultLevel:'',description:'Definición SFX creada desde el Lienzo.'});def=catalog('sfx',chosen)}const st=Number(prompt('Inicio en segundos:','0')),dur=+def.duration||.2,before=JSON.stringify(state.project),id=`${pid(p)}_${chosen}_${Date.now().toString().slice(-6)}`;p.timeline=p.timeline||[];const routes=availableRoutes(p);p.timeline.push({id,track:'sfx',type:'sfx',definitionId:chosen,label:def.name||chosen,start:st,end:st+dur,timingMode:'free',...(routes.length>1?{routes:[currentRoute(p)]}:{}),sfx:{name:def.name||chosen,search:def.search||'',purpose:def.purpose||'',mix:def.defaultLevel||'',status:'pending_selection'}});checkpoint('Crear SFX',before);state.selectedEventId=id;render()}
function exportJSON(){download(`${state.project.projectId||'ABRXOS'}_V3.json`,JSON.stringify(state.project,null,2),'application/json')}
function exportHTML(){const root=document.documentElement.cloneNode(true),script=root.querySelector('#app-data');script.textContent=JSON.stringify(state.project).replace(/<\/script>/gi,'<\\/script>');download(`${state.project.projectId||'ABRXOS'}_${state.project.renderer?.id||'renderer'}_V3.html`,'<!doctype html>\n'+root.outerHTML,'text/html')}
function download(name,text,type){const a=document.createElement('a'),blob=new Blob([text],{type});a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),800)}
restoreLocal();window.ABRXOS={state,baseDocument:base,getEvent,getPiece,render,setScheduleDate,catalog,createXRDefinition,createSFXDefinition,mergeProjects,undo,redo};render();
})();
