(()=>{'use strict';
const AB=window.ABRXOS;if(!AB||!AB.state)return;
const FAMILY_LABELS={COMIC_INFO:'Comic Info',COMIC_CC:'Comic CC',TYPO:'Typo / Letras',PHOTOS:'Fotos',OBJECTS:'Objetos',PHOTO_OBJECT:'Foto + Objeto',NO_XR:'No X-Roll / A-Roll'};
const PROFILE_LABELS={XR_FULL:'Cinematic Edit',MOTION_SFX:'Dynamic Edit',SFX_ONLY:'Clean Edit'};
const CHECKLIST=['editorial','source','cut','xr','images','broll','cine','motion','sfx','music','captions','cover','copy','qa'];
const CHECK_OPTIONS=['pending','planned','ready','created','placed','approved','needs_review','blocked'];
const DONE=new Set(['ready','created','placed','approved','done','complete','completed','verified']);
let scheduled=false;
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function pretty(v){if(v===null||v===undefined||v==='')return '—';if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')return String(v);return JSON.stringify(v,null,2)}
function pieceId(p){return String(p?.canonicalId||p?.contentId||p?.id||'')}
function piece(){if(typeof AB.getPiece==='function'&&AB.state.selectedPieceId)return AB.getPiece(AB.state.selectedPieceId);return (AB.state.project?.pieces||[]).find(x=>pieceId(x)===AB.state.selectedPieceId)||(AB.state.project?.pieces||[])[0]||null}
function event(){return AB.state.selectedEventId&&typeof AB.getEvent==='function'?AB.getEvent(AB.state.selectedEventId):null}
function validationRow(p){return AB.state.project?.r6Validation?.pieces?.find(x=>String(x.id)===pieceId(p))||null}
function copy(text){if(navigator.clipboard?.writeText)navigator.clipboard.writeText(String(text??'')).catch(()=>{});else{const ta=document.createElement('textarea');ta.value=String(text??'');document.body.appendChild(ta);ta.select();document.execCommand?.('copy');ta.remove()}}
function persist(){try{const p=AB.state.project,key=`abrxos:v3:${p.projectId}:${p.canvas?.title||'canvas'}`;localStorage.setItem(key,JSON.stringify(p))}catch(e){}}
function progress(p){const c=p?.productionChecklist||{};let done=0;for(const k of CHECKLIST){const raw=c[k],s=String((raw&&typeof raw==='object'?raw.status:raw)||'pending').toLowerCase();if(DONE.has(s))done++}return Math.round(done/CHECKLIST.length*100)}
function infoCard(title,value,cls=''){return `<div class="r6-info-card ${cls}"><div class="r6-card-head"><small>${esc(title)}</small><button type="button" data-r6-copy="${esc(typeof value==='string'?value:pretty(value))}">Copiar</button></div><pre>${esc(pretty(value))}</pre></div>`}
function style(){if(document.getElementById('abrxos-r6-style'))return;const el=document.createElement('style');el.id='abrxos-r6-style';el.textContent=`
.r6-inspector{border:1px solid #51415f;background:linear-gradient(180deg,#17131f,#101014);border-radius:12px;padding:12px;margin:0 0 12px}.r6-inspector h3{margin:0 0 9px;font-size:13px}.r6-kicker{font-size:9px;letter-spacing:.8px;text-transform:uppercase;color:#c4a7f2}.r6-meta{display:flex;gap:5px;flex-wrap:wrap;margin:7px 0}.r6-pill{font-size:9px;border:1px solid #4d3a66;border-radius:999px;padding:2px 6px;color:#ddd0f7}.r6-info-card{border-top:1px solid #2f2937;padding:8px 0}.r6-info-card:first-of-type{border-top:0}.r6-card-head{display:flex;justify-content:space-between;gap:8px}.r6-card-head small{color:#b89ddd}.r6-card-head button{min-height:25px;padding:2px 6px;font-size:9px}.r6-info-card pre{white-space:pre-wrap;margin:5px 0 0;font:11px/1.55 ui-monospace,SFMono-Regular,monospace;color:#ddd}.r6-asset{border:1px solid #37313f;border-radius:8px;padding:9px;margin:7px 0;background:#121217}.r6-asset b{display:block}.r6-asset dl{display:grid;grid-template-columns:minmax(90px,130px) 1fr;gap:4px 8px;margin:7px 0;font-size:10px}.r6-asset dt{color:#9f95a8}.r6-asset dd{margin:0;white-space:pre-wrap}.r6-cue{border-left:2px solid #8b5cf6;padding:4px 7px;margin:4px 0;font-size:10px}.r6-caption-hidden{opacity:.38!important;filter:saturate(.35);outline:1px dashed #f59e0b!important}.r6-profile-badge{display:inline-flex;border:1px solid #5b3a82;background:#25143d;color:#e9d5ff;border-radius:999px;padding:3px 7px;font-size:9px}.r6-check-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.r6-check{display:grid;gap:3px;font-size:9px;color:#aaa}.r6-check select{min-width:0;padding:5px;font-size:9px}.r6-progress{height:5px;background:#28242f;border-radius:999px;overflow:hidden;margin:7px 0}.r6-progress i{display:block;height:100%;background:linear-gradient(90deg,#8b5cf6,#22c55e)}.r6-validation-line{font-size:10px;color:#c8c1ce}.r6-validation-line.warn{color:#fcd34d}.r6-validation-line.ok{color:#86efac}@media(max-width:760px){.r6-check-grid{grid-template-columns:1fr}.r6-inspector{padding:10px}}
`;document.head.appendChild(el)}
function profileBlock(p){const prof=p?.editProfile;if(!prof)return '';const code=typeof prof==='string'?prof:prof.code;const name=(typeof prof==='object'&&prof.commercialName)||PROFILE_LABELS[code]||code;return `<div class="r6-meta"><span class="r6-profile-badge">${esc(name)} · ${esc(code)}</span></div>`}
function validationBlock(p){const row=validationRow(p);if(!row)return '';const cls=row.alphaReady?'ok':'warn';return `<div class="r6-validation-line ${cls}">Alpha ${row.alphaReady?'READY':'REVIEW'} · Cutter ${row.cutterReady?'READY':'REVIEW'} · ${row.progressPercent??progress(p)}%</div>${(row.missing||[]).length?`<div class="r6-validation-line warn">Falta: ${esc((row.missing||[]).join(' · '))}</div>`:''}`}
function checklistBlock(p){const c=p?.productionChecklist||{},pct=progress(p);return `<div class="r6-info-card"><div class="r6-card-head"><small>PRODUCTION CHECKLIST</small><b data-r6-progress-label>${pct}%</b></div><div class="r6-progress"><i data-r6-progress-bar style="width:${pct}%"></i></div><div class="r6-check-grid">${CHECKLIST.map(k=>{const raw=c[k],status=String((raw&&typeof raw==='object'?raw.status:raw)||'pending');return `<label class="r6-check">${esc(k)}<select data-r6-checklist="${esc(k)}">${CHECK_OPTIONS.map(x=>`<option value="${x}" ${x===status?'selected':''}>${x}</option>`).join('')}</select></label>`}).join('')}</div></div>`}
function xrBlock(e){const fam=e.xrFamily||e.definitionId||'XR',label=FAMILY_LABELS[fam]||fam;let html=`<div class="r6-kicker">XR R6 · ${esc(fam)}</div><h3>${esc(label)}</h3><div class="r6-meta"><span class="r6-pill">${esc(e.start)} → ${esc(e.end)}</span><span class="r6-pill">Caption ${esc(e.captionPolicy||'AUTO')}</span></div>`;html+=infoCard('FUNCIÓN',e.function||'');html+=infoCard('ANCHOR TEXT',e.anchorText||e.sourceQuote||'');if(e.states?.length)html+=infoCard('STATES',e.states);if(e.assets?.length){html+=`<div class="r6-info-card"><small>ASSETS · ${e.assets.length}</small>${e.assets.map(a=>`<div class="r6-asset"><b>${esc(a.assetId||a.id||'ASSET')} · ${esc(a.assetType||a.type||'')}</b><dl><dt>Descripción</dt><dd>${esc(a.description||'')}</dd><dt>Context & Detail</dt><dd>${esc(a.contextAndDetail||'')}</dd><dt>Visible</dt><dd>${esc(a.whatIsVisible||'')}</dd><dt>Match discurso</dt><dd>${esc(a.whyItMatchesSpeech||'')}</dd><dt>Prompt</dt><dd>${esc(a.prompt||'')}</dd><dt>B-roll ref</dt><dd>${esc(a.brollReference||'')}</dd><dt>Google search</dt><dd>${esc(a.googleSearchQuery||'')}</dd><dt>Placement</dt><dd>${esc(a.placementRecommendation||'')}</dd><dt>Razón</dt><dd>${esc(a.placementReason||'')}</dd><dt>Emoji fallback</dt><dd>${esc((a.emojiFallback||[]).join(' · '))}</dd><dt>Duración</dt><dd>${esc(a.durationSeconds??((+a.end||0)-(+a.start||0)))} s</dd><dt>Status</dt><dd>${esc(a.status||'')}</dd></dl><button type="button" data-r6-copy="${esc(a.prompt||'')}">Copiar prompt</button></div>`).join('')}</div>`}return html}
function cineBlock(e){return `<div class="r6-kicker">CINE · T5</div><h3>${esc(e.cineType||e.label||'CINE')}</h3>${infoCard('FUNCIÓN',e.function||'')}${infoCard('VISUAL',e.visual||'')}${infoCard('MOTION',e.motionIds||e.motion||'')}${infoCard('SFX',e.sfxIds||e.sfx||'')}${infoCard('MUSIC AUTOMATION',e.musicAutomation||e.music||'')}${infoCard('Silencio',e.silence===true?'Sí':e.silence===false?'No':e.silence||'')}${infoCard('CAPTION POLICY',e.captionPolicy||'AUTO')}`}
function captionBlock(e){return `<div class="r6-kicker">CAPTION GROUP · R6</div><h3>${esc(e.id||'Caption')}</h3><div class="r6-meta"><span class="r6-pill">${esc(e.wordCount??String(e.sourceText||'').split(/\s+/).filter(Boolean).length)} palabras</span><span class="r6-pill">${esc(e.visibility||'visible')}</span><span class="r6-pill">${esc(e.displayMode||'normal')}</span></div>${infoCard('SOURCE TEXT',e.sourceText||e.text||'')}${infoCard('HIGHLIGHT',e.highlightWord||'')}${infoCard('SUPPRESSED BY',e.suppressedBy||'')}${(e.displayCues||[]).length?`<div class="r6-info-card"><small>DISPLAY CUES</small>${e.displayCues.map(c=>`<div class="r6-cue"><b>${esc(c.mode||'normal')}</b> · ${esc(c.start)}→${esc(c.end)}<br>${esc(c.text||'')}</div>`).join('')}</div>`:''}`}
function sfxBlock(e){const s=e.sfx&&typeof e.sfx==='object'?e.sfx:e;return `<div class="r6-kicker">SFX · R6 · T7</div><h3>${esc(e.label||s.libraryId||e.id||'SFX')}</h3><div class="r6-meta"><span class="r6-pill">${esc(e.start)} → ${esc(e.end)}</span><span class="r6-pill">${esc(s.status||'pending_selection')}</span></div>${infoCard('LIBRARY ID',s.libraryId||e.libraryId||e.definitionId||'')}${infoCard('VARIANT',s.variant||'')}${infoCard('TRIGGER',s.trigger||'')}${infoCard('PURPOSE',s.purpose||'')}${infoCard('PLACEMENT',s.placement||s.placementTemporal||'')}${infoCard('MIX / DUCKING',s.mix||s.ducking||'')}${infoCard('STATUS',s.status||'')}`}
function genericAssetBlock(e){const a=e.asset||e;return `<div class="r6-kicker">R6 ASSET</div><h3>${esc(e.label||a.assetId||e.id||'Asset')}</h3>${infoCard('CONTEXT & DETAIL',a.contextAndDetail||'')}${infoCard('WHAT IS VISIBLE',a.whatIsVisible||a.description||'')}${infoCard('WHY MATCHES SPEECH',a.whyItMatchesSpeech||'')}${infoCard('PROMPT',a.prompt||'')}${infoCard('B-ROLL / SEARCH',a.brollReference||a.googleSearchQuery||'')}${infoCard('PLACEMENT',`${a.placementRecommendation||''}${a.placementReason?' · '+a.placementReason:''}`)}${infoCard('EMOJI FALLBACK',a.emojiFallback||[])}`}
function eventBlock(e){if(e?.track==='xr'&&(FAMILY_LABELS[e.xrFamily]||e.xrFamily==='NO_XR'))return xrBlock(e);if(e?.track==='broll'&&e?.type==='cine')return cineBlock(e);if(e?.track==='captions'&&(e?.type==='caption_group'||e?.captionPolicyVersion==='R6'))return captionBlock(e);if(e?.track==='sfx')return sfxBlock(e);if(e?.track==='images'||e?.type==='object'||e?.asset?.contextAndDetail)return genericAssetBlock(e);return ''}
function bind(root,p){root.querySelectorAll('[data-r6-copy]').forEach(b=>b.onclick=()=>copy(b.dataset.r6Copy||''));root.querySelectorAll('[data-r6-checklist]').forEach(sel=>sel.onchange=()=>{p.productionChecklist=p.productionChecklist&&typeof p.productionChecklist==='object'?p.productionChecklist:{};const k=sel.dataset.r6Checklist,existing=p.productionChecklist[k];p.productionChecklist[k]=typeof existing==='object'&&existing?{...existing,status:sel.value}:{status:sel.value};persist();const pct=progress(p),lab=root.querySelector('[data-r6-progress-label]'),bar=root.querySelector('[data-r6-progress-bar]');if(lab)lab.textContent=`${pct}%`;if(bar)bar.style.width=`${pct}%`})}
function markHiddenCaptions(){document.querySelectorAll('[data-event-id]').forEach(el=>{const id=el.dataset.eventId,e=typeof AB.getEvent==='function'?AB.getEvent(id):null;el.classList.toggle('r6-caption-hidden',!!(e&&e.track==='captions'&&e.visibility==='hidden'))})}
function decorate(){scheduled=false;style();markHiddenCaptions();const p=piece(),root=document.querySelector('#inspector');if(!p||!root)return;const e=event(),key=e?`event:${e.id}`:`piece:${pieceId(p)}`;if(root.querySelector(`.r6-inspector[data-r6-for="${CSS.escape(key)}"]`))return;root.querySelectorAll('.r6-inspector').forEach(x=>x.remove());const box=document.createElement('section');box.className='r6-inspector';box.dataset.r6For=key;let html=`${profileBlock(p)}${validationBlock(p)}`;if(e){const detail=eventBlock(e);if(!detail)return;html+=detail}else{html+=`<div class="r6-kicker">FICHA / PRODUCCIÓN</div><h3>${esc(p.title||pieceId(p))}</h3>${checklistBlock(p)}`};box.innerHTML=html;root.prepend(box);bind(box,p);const actions=document.querySelector('.pieceactions');if(actions&&p.editProfile&&!actions.querySelector('.r6-profile-badge')){const span=document.createElement('span');span.className='r6-profile-badge';const prof=p.editProfile,code=typeof prof==='string'?prof:prof.code,name=(typeof prof==='object'&&prof.commercialName)||PROFILE_LABELS[code]||code;span.textContent=`${name} · ${code}`;actions.prepend(span)}}
function schedule(){if(scheduled)return;scheduled=true;queueMicrotask(decorate)}
const originalRender=typeof AB.render==='function'?AB.render.bind(AB):null;if(originalRender)AB.render=function(...args){const result=originalRender(...args);schedule();return result};
const observer=new MutationObserver(()=>schedule());observer.observe(document.documentElement,{childList:true,subtree:true});
window.ABRXOS_R6={version:'3.1-r6',ready:true,decorate,persist,progress,FAMILY_LABELS,PROFILE_LABELS};
schedule();
})();
